In [1]:
import torch

# Tensors

### Initialize an Empty Tesnsor

Sometimes will be zero, other times a value very close to zero

In [19]:
a = torch.empty(1)
b = torch.empty(3)
c = torch.empty(2, 3)
print(a, b, c, sep='\n')

tensor([2.3694e-38])
tensor([2.3694e-38, 7.1877e-01, 0.0000e+00])
tensor([[-3.7011e-04,  1.3452e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


### Initialize a Tensor with ones or zeros

In [22]:
a = torch.ones(2, 2)
b = torch.zeros(3, 3)
print(a, b, sep='\n')

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Initialize a random number between 0 and 1

In [20]:
torch.rand(2, 3, 3)

tensor([[[0.8856, 0.8617, 0.8179],
         [0.5161, 0.6591, 0.0127],
         [0.2836, 0.1166, 0.8899]],

        [[0.3839, 0.8613, 0.4790],
         [0.6122, 0.3970, 0.3158],
         [0.0431, 0.8514, 0.8206]]])

## Size and Data type

In [24]:
print(a.shape, a.size(), a.dtype)

torch.Size([2, 2]) torch.Size([2, 2]) torch.float32


In [25]:
a = torch.zeros(5, 3, dtype=torch.long)
a

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### Construct from Data

In [27]:
a = torch.tensor([[1,2,3], [5, 4,2], [0,9,1]])
a

tensor([[1, 2, 3],
        [5, 4, 2],
        [0, 9, 1]])

In [28]:
import numpy as np
b = np.array([[2, 4, 5], [1, 9, 2]])
a =  torch.tensor(b)
a

tensor([[2, 4, 5],
        [1, 9, 2]], dtype=torch.int32)

## Requires Grad

Requires grad argument will tell pytorch that it will need to calculate the gradient for this tensor in the optimization steps (this is a variavble in the model we eant to optimize)

By default is 'Deacticated' or False

In [29]:
a = torch.rand(3, 4, requires_grad=True)
a

tensor([[0.7455, 0.3828, 0.8184, 0.4690],
        [0.3194, 0.6442, 0.7646, 0.1641],
        [0.0614, 0.1080, 0.7622, 0.2319]], requires_grad=True)

## Operations
- Addition
- Substraction
- Multiplication 
- Division

The tensors involved in the operatiosn must match shapes, since the operations are elementwise

In [30]:
b = torch.ones(4, 3)
a + b

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [31]:
b = torch.ones(3, 4)
a + b

tensor([[1.7455, 1.3828, 1.8184, 1.4690],
        [1.3194, 1.6442, 1.7646, 1.1641],
        [1.0614, 1.1080, 1.7622, 1.2319]], grad_fn=<AddBackward0>)

In [32]:
a - b

tensor([[-0.2545, -0.6172, -0.1816, -0.5310],
        [-0.6806, -0.3558, -0.2354, -0.8359],
        [-0.9386, -0.8920, -0.2378, -0.7681]], grad_fn=<SubBackward0>)

In [39]:
a = torch.tensor([[1, 1, 1], [2, 2, 2]])
b = torch.tensor([2, 3, 4])
print(torch.mul(a, b))
b * a

tensor([[2, 3, 4],
        [4, 6, 8]])


tensor([[2, 3, 4],
        [4, 6, 8]])

In [40]:
print(torch.div(a, b))
a/b

tensor([[0.5000, 0.3333, 0.2500],
        [1.0000, 0.6667, 0.5000]])


tensor([[0.5000, 0.3333, 0.2500],
        [1.0000, 0.6667, 0.5000]])

In [43]:
a[0, -1].item()

1

## View and Reshape

- View: It only works if the tensor is "contiguous" in memory. It does not  copy the data, but rather creates a new view of the same data
- Reshape: Can return either a view of the original tensor or a copy

In [52]:
# View
x = torch.ones(2, 4)
print(x)
y = x.view(4, 2)  # torch.Size([2, 8])
print(y)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [53]:
y += 2
x, y

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3.],
         [3., 3.],
         [3., 3.],
         [3., 3.]]))

In [56]:
# Reshape
x = torch.ones(2, 4)
print(x)
y = x.reshape(4, 2)  # torch.Size([2, 8])
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [57]:
y += 2
x, y

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3.],
         [3., 3.],
         [3., 3.],
         [3., 3.]]))

## Gpu Support

By default all tensors are created on the CPU. But we can also move them to the GPU ( if it is available)

In [59]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [60]:
a = torch.rand(2, 4)
a.to(device)
# x.to('cuda')
# x.to('cpu')

tensor([[0.2268, 0.3845, 0.8007, 0.0342],
        [0.7608, 0.5396, 0.7537, 0.1929]])

In [61]:
a = torch.rand(2,2, device=device)